#!/bin/bash

# TODO: generate this file... termite should handle it!
if ! [ -d node_modules/ ]; then
	npm i
fi

etc/rootCA.pem

SCRIPT=${1:-/usr/local/bin}/srvr
cat > $SCRIPT <<EOM
#!/bin/bash

$(pwd)/srvr.js \$@

EOM
chmod +x $SCRIPT
# And that should do it!
echo "INSTALLED @ $SCRIPT"